### ISSUE TITLE
使用deployment Profiles做package，有错误！

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#10]
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3119:column 39:missing formal parameter
	function SVGNodeContainer(node, native) {
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3119:column 39:missing } after function body
	function SVGNodeContainer(node, native) {
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3120:column 10:syntax error
	    this.src = node;
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3124:column 26:identifier is a reserved word
	    this.promise = native ? new Promise(function(resolve, reject) {
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3125:column 14:syntax error
	        self.image = new Image();
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3132:column 5:syntax error
	    }) : this.hasFabric().then(function() {
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3136:column 5:syntax error
	    });
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3137:column 1:syntax error
	}
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3139:column 18:syntax error
	SVGNodeContainer.prototype = Object.create(SVGContainer.prototype);
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 3375:column 1:syntax error
	}).call({}, typeof(window) !== "undefined" ? window : undefined, typeof(document) !== "undefined" ? document : undefined);
[ERROR] .../src/main/webapp/assets/apps/plugins/html2canvas/html2canvas.js:line 1:column 0:Compilation produced 10 syntax errors.

**Comment by xautlx** [comment]
Fixed：https://github.com/xautlx/s2jh4net/commit/43f6da56f8113fc2e45fdd6334eeef74ede7e1be
