### ISSUE TITLE
登录页面的Remember Me没有起作用

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#12]
勾选了记住我，同时也看到了Cookie中的RememberMe的token，但关闭浏览器后，再次访问时，还是跳到登录页面，而没有实现自动登录。

**Comment by xautlx** [comment]
rememberme需要在user级别才有效，以便用在前端用户界面，目前管理端定义的是authc级别是会强制转向登录界面的。可能考虑是把管理端登录界面的rememberme选项去掉，毕竟后台管理端记住我好像不太安全。

**Comment by xautlx** [comment]
管理端登录移除remembme功能，后面的前端用户界面采用rememberme特性
