### ISSUE TITLE
kindeditor经常加载的内容不显示

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#23]
<form:textarea id="" path="content" class="form-control"
                                       data-htmleditor='kindeditor'
                                       data-height="400"/>
内容经常加载不出来，打开编辑页面，编辑器里边空白，并且不能激活，内容也没有丢失，只是没有显示出来，点保存还能保存

**Comment by xautlx** [comment]
问题好像出在弹窗与kindeditor交互层面，重新显示弹窗就不显示kindeditor内容了

**Comment by xautlx** [comment]
Fixed
