### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by andyadc** [xautlx/s2jh4net#26]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoDatabase
DataInitializeProcessor': Unsatisfied dependency expressed through field 'attachmentFileStoreService'; nested exception
is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.entdiy.sys.service.A
ttachmentFileStoreService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotat
ions: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.entdiy.sys.s
ervice.AttachmentFileStoreService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency
 annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by xautlx** [comment]
Fixed
