### ISSUE TITLE
jcaptcha下载imaging失败

### ISSUE THREAD

**Issue by irayslu** [xautlx/s2jh4net#4]
设置http://jcaptcha.sourceforge.net/jcaptcha/dependencies.html中repo,但是发生
Archive for required library: 'D:/opt/maven/repository/com/jhlabs/imaging/01012005/imaging-01012005.jar' in project 's2jh4net' cannot be read or is not a valid ZIP file

**Comment by xautlx** [comment]
这个imaging组件资源库不稳定，好像又改名了，建议网上下载后手工放到maven 本地资源库

**Comment by irayslu** [comment]
我已经下载了,项目编译成功后里面还有好多的错啊,是不是不哪里出错了

**Comment by xautlx** [comment]
估计是lombok插件没安装，详见文档说明：https://github.com/xautlx/s2jh4net/blob/master/src/main/webapp/docs/markdown/%E5%BC%80%E5%8F%91%E9%85%8D%E7%BD%AE.md
