### ISSUE TITLE
配置redis服务器

### ISSUE THREAD

**Issue by hanyou** [xautlx/s2jh4net#9]
文档中没有地方提到需要配置redis服务器，但没有redis根本就跑不起来！
主要配置还要改两个地方，一个是hibernate-redisson.yaml，一个是application.properties，这是为什么？

**Comment by xautlx** [comment]
hibernate-redisson 采用 yaml文件格式，和 .properties 处理方式不一样，尝试过整合到一个地方配置，但是暂时没有找到好的方法，只能同时修改两个文件。

**Comment by xautlx** [comment]
添加 Docker服务.md 文档；更新文档添加Redis环境配置； https://gitee.com/xautlx/s2jh4net/commit/d412767a32f1715ad240cb4dac961519533ae863
